sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t devacc76/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true devacc76/docker-react npm run test
